# Generated by Django 5.2.8 on 2025-11-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMetrics',
            fields=[
                ('node_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('retweets', models.IntegerField()),
            ],
        ),
    ]
