# Generated by Django 5.2.8 on 2025-11-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_contentvariant_platform'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodemetrics',
            name='node_id',
        ),
        migrations.AddField(
            model_name='nodemetrics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='nodemetrics',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agents.post'),
            preserve_default=False,
        ),
    ]
