# Generated by Django 5.2.8 on 2025-11-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_alter_contentvariant_platform"),
        ("metrics", "0002_remove_nodemetrics_node_id_nodemetrics_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("retweets", models.IntegerField(default=0)),
                ("tweet_id", models.CharField(max_length=50)),
                (
                    "post_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agents.post"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NodeMetrics",
        ),
    ]
