# Generated by Django 5.2.8 on 2025-11-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_postmetrics_delete_nodemetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='post_object',
        ),
    ]
