# Generated by Django 5.2.8 on 2025-11-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_remove_postmetrics_post_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='impressions',
        ),
    ]
