# Generated by Django 5.2.8 on 2025-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_postmetrics_impressions'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('post_id', models.CharField(max_length=50)),
            ],
        ),
    ]
