# Generated by Django 5.2.8 on 2025-11-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_igmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igmetrics',
            old_name='comments',
            new_name='shares',
        ),
    ]
