# Generated by Django 5.2.8 on 2025-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_rename_comments_igmetrics_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetrics',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
    ]
