# Generated by Django 5.2.8 on 2025-11-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_postmetrics_impressions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IGMetrics',
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='commentList',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
