# Generated by Django 5.2.8 on 2025-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0009_delete_igmetrics_postmetrics_commentlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmetrics",
            name="tweet_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
