# Generated by Django 5.2.8 on 2025-11-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Agent Memories",
                "indexes": [
                    models.Index(
                        fields=["agent_name"], name="agents_agen_agent_n_af1968_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("content_creation", "Content Creation"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                        ],
                        default="planning",
                        max_length=50,
                    ),
                ),
                (
                    "strategy",
                    models.TextField(
                        blank=True,
                        help_text="Mermaid diagram representation",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("insights", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["campaign_id"], name="agents_camp_campaig_78c677_idx"
                    ),
                    models.Index(fields=["phase"], name="agents_camp_phase_7b13cf_idx"),
                    models.Index(
                        fields=["-created_at"], name="agents_camp_created_b3359e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("phase", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("analyzed", "Analyzed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "selected_variant",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="agents.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_id", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("platform", models.CharField(default="x", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="agents.post",
                    ),
                ),
            ],
            options={
                "ordering": ["variant_id"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="agents.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="agents_conv_created_bfeade_idx"
                    ),
                    models.Index(
                        fields=["campaign", "created_at"],
                        name="agents_conv_campaig_404027_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["post_id"], name="agents_post_post_id_14afa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["campaign", "status"], name="agents_post_campaig_3aa8af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="agents_post_created_d163b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentvariant",
            index=models.Index(
                fields=["post", "variant_id"], name="agents_cont_post_id_403b6a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentvariant",
            unique_together={("post", "variant_id")},
        ),
    ]
