# Generated by Django 5.2.8 on 2025-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentvariant",
            name="platform",
            field=models.CharField(choices=[("X", "X")], default="X", max_length=50),
        ),
    ]
