# Generated by Django 5.2.8 on 2025-11-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_contentvariant_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="next_posts",
            field=models.ManyToManyField(
                blank=True, related_name="previous_posts", to="agents.post"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="phase",
            field=models.CharField(
                choices=[
                    ("Phase 1", "Phase 1"),
                    ("Phase 2", "Phase 2"),
                    ("Phase 3", "Phase 3"),
                ],
                default="Phase 1",
                max_length=10,
            ),
        ),
    ]
