# Generated by Django 5.2.8 on 2025-11-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_alter_contentvariant_platform"),
        ("metrics", "0003_postmetrics_delete_nodemetrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="metrics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metrics.postmetrics",
            ),
        ),
    ]
