# Generated by Django 5.2.8 on 2025-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_alter_post_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.CharField(max_length=255),
        ),
    ]
