# Generated by Django 5.2.8 on 2025-11-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_post_description_post_next_posts_post_title_and_more'),
        ('agents', '0004_alter_post_post_id'),
    ]

    operations = [
    ]
