# Generated by Django 5.2.8 on 2025-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_merge_20251108_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
