# Generated by Django 5.2.8 on 2025-11-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_alter_post_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentvariant",
            name="asset",
            field=models.FileField(
                blank=True, null=True, upload_to="content_variants/"
            ),
        ),
    ]
