# Generated by Django 5.2.8 on 2025-11-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_contentvariant_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trigger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
