# Generated by Django 5.2.8 on 2025-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_post_trigger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="trigger",
        ),
        migrations.AddField(
            model_name="post",
            name="posted_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when post was published to X/Twitter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="trigger_comparison",
            field=models.CharField(
                blank=True,
                choices=[("<", "Less than"), ("=", "Equal to"), (">", "Greater than")],
                help_text="Comparison operator (<, =, >)",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="trigger_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("likes", "Likes"),
                    ("retweets", "Retweets"),
                    ("impressions", "Impressions"),
                    ("comments", "Comments"),
                ],
                help_text="Metric to monitor (likes, retweets, impressions, comments)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="trigger_prompt",
            field=models.TextField(
                blank=True,
                help_text="Action prompt when trigger is activated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="trigger_value",
            field=models.IntegerField(
                blank=True, help_text="Threshold value for trigger", null=True
            ),
        ),
    ]
