# Generated by Django 5.2.8 on 2025-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_remove_post_trigger_post_posted_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentvariant",
            options={"ordering": ["-created_at", "variant_id"]},
        ),
        migrations.RemoveIndex(
            model_name="contentvariant",
            name="agents_cont_post_id_403b6a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="contentvariant",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="contentvariant",
            index=models.Index(
                fields=["post", "variant_id", "-created_at"],
                name="agents_cont_post_id_fcc4dc_idx",
            ),
        ),
    ]
