# Generated by Django 5.2.8 on 2025-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0010_alter_contentvariant_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="trigger_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum elapsed time in seconds before trigger can fire",
                null=True,
            ),
        ),
    ]
