# Generated by Django 5.2.8 on 2025-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_post_trigger_duration"),
        ("metrics", "0011_convert_to_ab_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="current_version",
            field=models.IntegerField(
                default=1, help_text="Current version number for strategy regeneration"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this post is currently active (False for archived versions)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Version number of this post"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["campaign", "is_active"], name="agents_post_campaig_cff009_idx"
            ),
        ),
    ]
