# Generated by Django 5.2.8 on 2025-11-08 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('text', models.TextField(max_length=280)),
                ('media_image', models.ImageField(blank=True, null=True, upload_to='tweets/images/')),
                ('media_video', models.FileField(blank=True, null=True, upload_to='tweets/videos/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text Only')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_reply_to_tweet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloneRetweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='twitter_clone.clonetweet')),
            ],
        ),
        migrations.CreateModel(
            name='CloneLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twitter_clone.clonetweet')),
            ],
        ),
        migrations.CreateModel(
            name='CloneImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='twitter_clone.clonetweet')),
            ],
        ),
        migrations.CreateModel(
            name='CloneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='twitter_clone.clonetweet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clonetweet',
            index=models.Index(fields=['tweet_id'], name='twitter_clo_tweet_i_76dd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='clonetweet',
            index=models.Index(fields=['-created_at'], name='twitter_clo_created_e4941a_idx'),
        ),
        migrations.AddIndex(
            model_name='cloneretweet',
            index=models.Index(fields=['original_tweet', 'user'], name='twitter_clo_origina_a0f604_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cloneretweet',
            unique_together={('original_tweet', 'user')},
        ),
        migrations.AddIndex(
            model_name='clonelike',
            index=models.Index(fields=['tweet', 'user'], name='twitter_clo_tweet_i_f85717_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clonelike',
            unique_together={('tweet', 'user')},
        ),
        migrations.AddIndex(
            model_name='cloneimpression',
            index=models.Index(fields=['tweet'], name='twitter_clo_tweet_i_c51ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='clonecomment',
            index=models.Index(fields=['tweet', '-created_at'], name='twitter_clo_tweet_i_435ad3_idx'),
        ),
    ]
